# Use the official Nginx Alpine image
FROM nginx:alpine

# Copy your local config from the Jenkins workspace into the image
# This is the "Baking" process that fixes the mount error
COPY nginx.conf /etc/nginx/nginx.conf

